name: assertable_json
description: A package that provides a way to assert JSON objects.
version: 0.1.0
homepage: https://github.com/kingwill101/assertable_json

topics: 
  - json
  - testing
  - assertions

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  test: ^1.24.0

dev_dependencies:
  lints: ^5.0.0

funding:
  - https://www.buymeacoffee.com/kingwill101
